// Mocks generated by Mockito 5.4.6 from annotations
// in corrupt/test/api/fafu/fafu_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cirno_pref_key/cirno_pref.dart' as _i6;
import 'package:corrupt/features/pref/domain/abstract_repository/abstract_raw_local_data.dart'
    as _i5;
import 'package:corrupt/features/subchannels/fafu/domain/abstract_repository/fafu_api_raw.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FafuApiRaw].
///
/// See the documentation for Mockito's code generation for more information.
class MockFafuApiRaw extends _i1.Mock implements _i4.FafuApiRaw {
  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getLoginPage() =>
      (super.noSuchMethod(
            Invocation.method(#getLoginPage, []),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getLoginPage, []),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getLoginPage, []),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getCheckCode({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCheckCode, [], {#token: token}),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getCheckCode, [], {#token: token}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getCheckCode, [], {#token: token}),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getMainPage({
    required String? token,
    required String? studentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMainPage, [], {
              #token: token,
              #studentId: studentId,
            }),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getMainPage, [], {
                  #token: token,
                  #studentId: studentId,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getMainPage, [], {
                      #token: token,
                      #studentId: studentId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getClassesPageDefault({
    required String? token,
    required String? studentId,
    required String? studentName,
    required String? referer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClassesPageDefault, [], {
              #token: token,
              #studentId: studentId,
              #studentName: studentName,
              #referer: referer,
            }),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getClassesPageDefault, [], {
                  #token: token,
                  #studentId: studentId,
                  #studentName: studentName,
                  #referer: referer,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getClassesPageDefault, [], {
                      #token: token,
                      #studentId: studentId,
                      #studentName: studentName,
                      #referer: referer,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getClassesPage({
    required String? token,
    required String? studentId,
    required String? studentName,
    required String? viewState,
    required String? academicYear,
    required String? semester,
    String? eventTarget = '',
    String? eventTArgument = '',
    required String? referer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClassesPage, [], {
              #token: token,
              #studentId: studentId,
              #studentName: studentName,
              #viewState: viewState,
              #academicYear: academicYear,
              #semester: semester,
              #eventTarget: eventTarget,
              #eventTArgument: eventTArgument,
              #referer: referer,
            }),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getClassesPage, [], {
                  #token: token,
                  #studentId: studentId,
                  #studentName: studentName,
                  #viewState: viewState,
                  #academicYear: academicYear,
                  #semester: semester,
                  #eventTarget: eventTarget,
                  #eventTArgument: eventTArgument,
                  #referer: referer,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getClassesPage, [], {
                      #token: token,
                      #studentId: studentId,
                      #studentName: studentName,
                      #viewState: viewState,
                      #academicYear: academicYear,
                      #semester: semester,
                      #eventTarget: eventTarget,
                      #eventTArgument: eventTArgument,
                      #referer: referer,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getExamPageDefault({
    required String? token,
    required String? studentId,
    required String? studentName,
    required String? referer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExamPageDefault, [], {
              #token: token,
              #studentId: studentId,
              #studentName: studentName,
              #referer: referer,
            }),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getExamPageDefault, [], {
                  #token: token,
                  #studentId: studentId,
                  #studentName: studentName,
                  #referer: referer,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getExamPageDefault, [], {
                      #token: token,
                      #studentId: studentId,
                      #studentName: studentName,
                      #referer: referer,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getExamPage({
    required String? token,
    required String? studentId,
    required String? studentName,
    required String? viewState,
    required String? academicYear,
    required String? semester,
    String? eventTarget = '',
    String? eventTArgument = '',
    required String? referer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExamPage, [], {
              #token: token,
              #studentId: studentId,
              #studentName: studentName,
              #viewState: viewState,
              #academicYear: academicYear,
              #semester: semester,
              #eventTarget: eventTarget,
              #eventTArgument: eventTArgument,
              #referer: referer,
            }),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getExamPage, [], {
                  #token: token,
                  #studentId: studentId,
                  #studentName: studentName,
                  #viewState: viewState,
                  #academicYear: academicYear,
                  #semester: semester,
                  #eventTarget: eventTarget,
                  #eventTArgument: eventTArgument,
                  #referer: referer,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getExamPage, [], {
                      #token: token,
                      #studentId: studentId,
                      #studentName: studentName,
                      #viewState: viewState,
                      #academicYear: academicYear,
                      #semester: semester,
                      #eventTarget: eventTarget,
                      #eventTArgument: eventTArgument,
                      #referer: referer,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getScorePageDefault({
    required String? token,
    required String? studentId,
    required String? studentName,
    required String? referer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getScorePageDefault, [], {
              #token: token,
              #studentId: studentId,
              #studentName: studentName,
              #referer: referer,
            }),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getScorePageDefault, [], {
                  #token: token,
                  #studentId: studentId,
                  #studentName: studentName,
                  #referer: referer,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getScorePageDefault, [], {
                      #token: token,
                      #studentId: studentId,
                      #studentName: studentName,
                      #referer: referer,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getScorePage({
    required String? token,
    required String? studentId,
    required String? studentName,
    required String? viewState,
    required String? academicYear,
    required String? semester,
    String? eventTarget = '',
    String? eventTArgument = '',
    String? queryButton = '+%B2%E9++%D1%AF+',
    required String? referer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getScorePage, [], {
              #token: token,
              #studentId: studentId,
              #studentName: studentName,
              #viewState: viewState,
              #academicYear: academicYear,
              #semester: semester,
              #eventTarget: eventTarget,
              #eventTArgument: eventTArgument,
              #queryButton: queryButton,
              #referer: referer,
            }),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getScorePage, [], {
                  #token: token,
                  #studentId: studentId,
                  #studentName: studentName,
                  #viewState: viewState,
                  #academicYear: academicYear,
                  #semester: semester,
                  #eventTarget: eventTarget,
                  #eventTArgument: eventTArgument,
                  #queryButton: queryButton,
                  #referer: referer,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getScorePage, [], {
                      #token: token,
                      #studentId: studentId,
                      #studentName: studentName,
                      #viewState: viewState,
                      #academicYear: academicYear,
                      #semester: semester,
                      #eventTarget: eventTarget,
                      #eventTArgument: eventTArgument,
                      #queryButton: queryButton,
                      #referer: referer,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> getScorePageManually({
    required String? token,
    required String? studentId,
    required String? studentName,
    required String? referer,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getScorePageManually, [], {
              #token: token,
              #studentId: studentId,
              #studentName: studentName,
              #referer: referer,
              #body: body,
            }),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getScorePageManually, [], {
                  #token: token,
                  #studentId: studentId,
                  #studentName: studentName,
                  #referer: referer,
                  #body: body,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#getScorePageManually, [], {
                      #token: token,
                      #studentId: studentId,
                      #studentName: studentName,
                      #referer: referer,
                      #body: body,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i3.Future<_i2.HttpResponse<dynamic>> submitLogin({
    required String? token,
    required String? referer,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitLogin, [], {
              #token: token,
              #referer: referer,
              #body: body,
            }),
            returnValue: _i3.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#submitLogin, [], {
                  #token: token,
                  #referer: referer,
                  #body: body,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.HttpResponse<dynamic>>.value(
                  _FakeHttpResponse_0<dynamic>(
                    this,
                    Invocation.method(#submitLogin, [], {
                      #token: token,
                      #referer: referer,
                      #body: body,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i2.HttpResponse<dynamic>>);
}

/// A class which mocks [LocalRawDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalRawDataRepository extends _i1.Mock
    implements _i5.LocalRawDataRepository {
  @override
  _i3.Future<T> getData<OT, T>(_i6.CirnoPrefKey<OT, T>? key) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [key]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#getData, [key]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(this, Invocation.method(#getData, [key])),
            returnValueForMissingStub:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#getData, [key]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(this, Invocation.method(#getData, [key])),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<void> setData<OT, T>(_i6.CirnoPrefKey<OT, T>? key, T? t) =>
      (super.noSuchMethod(
            Invocation.method(#setData, [key, t]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
